### PR TITLE
convert tests to pytest

### PR DESCRIPTION
**Pull request by jswhit**

### CODE REVIEW

**Comment by jswhit** [comment]
@snowman2 - I switched config.sh from nose2 to py.test, but tests are failing.  Can you take a look?

**Comment by snowman2** [comment]
It looks good to me.

**Comment by jswhit** [comment]
Lots of errors like this:

`(Internal Proj Error: proj_create: no database context specified)`

**Comment by snowman2** [comment]
Uh oh. Nothing that I would think would cause this has occurred .. similar to the windows wheel build issues.

**Comment by jswhit** [comment]
Does the PROJ_LIB env var need to be set before running the tests?

**Comment by snowman2** [comment]
No, it should find the internal proj data dir without that. I am wondering if the test_data_directory is impacting the rest of the tests.

**Comment by snowman2** [comment]
I just realized the problem I think. I will make a PR later for pyproj. It is testing related, so if tests pass here, it should be fine to release.

**Comment by snowman2** [comment]
One way you could skip the data directory tests is:
```
pytest -k "not data_dir" -v -s
```

This is what happens for me:
```
$ pytest -k "not data_dir"
============================= test session starts =============================
platform linux -- Python 3.6.7, pytest-4.4.0, py-1.8.0, pluggy-0.9.0
rootdir: /home/snowal/scripts/pyproj
plugins: cov-2.6.1
collected 79 items / 7 deselected / 72 selected                               

test/test_awips221.py .                                                 [  1%]
test/test_crs.py ...............................                        [ 44%]
test/test_crs_cf.py .                                                   [ 45%]
test/test_datum.py .                                                    [ 47%]
test/test_datum_shift.py ....                                           [ 52%]
test/test_doctest_wrapper.py .                                          [ 54%]
test/test_exception_logging.py ..                                       [ 56%]
test/test_geod.py ..                                                    [ 59%]
test/test_pickle.py .                                                   [ 61%]
test/test_transform.py .                                                [ 62%]
test/test_transformer.py ...........................                    [100%]

```

**Comment by snowman2** [comment]
Looks like the tests we care about are passing with the last commit.

**Comment by snowman2** [comment]
The `cd ../pyproj` may not be needed. I don't have a good reason for it to be there except an assumption.

**Comment by jswhit** [comment]
Some tests are failing, so not all wheels are uploaded.  Should I just disable the tests?

**Comment by snowman2** [comment]
I think disabling the tests it a good idea 👍. Much clearer for what we expect.

**Comment by snowman2** [comment]
Keeping the tests as and disabling specific failing platforms is what I was thinking. The ones that are failing should probably not have wheels.

**Comment by jswhit** [comment]
Puzzling thing is all the tests pass in the main repo, for python2.7 and 3.x.

**Comment by snowman2** [comment]
They do. Some of the 2.7 builds work as well as some of the 3.x wheels. We test for `x86_64`, and all of those wheels build. But, we don't test for the `i686` platforms or the `pypy` builds. Some of those fail for 2.7 and for 3.5.

**Pull request merged**
