### PR TITLE
manylinux_2_24

### PR DESCRIPTION
**Pull request by snowman2**
https://github.com/pyproj4/pyproj/issues/933

### CODE REVIEW

**Comment by snowman2** [comment]
@rouault, I am getting this error: `Internal Proj Error: curl_easy_setopt at line 1605 failed` for the `aarch64` architecture when building more modern wheels [ref](https://app.travis-ci.com/github/pyproj4/pyproj-wheels/jobs/536093291#L3962). Does this mean anything to you?

Python code to reproduce (essentially `cs2cs`):
```python
transformer = Transformer.from_proj("+init=epsg:4326", "+init=epsg:27700")
transformer.transform(1.716073972, 52.658007833, errcheck=True)
```

**Comment by snowman2** [comment]
Going to merge to get the `x86_64` wheels on pypi with the fix. Moved issue out error here: https://github.com/pyproj4/pyproj-wheels/issues/38

**Comment by rouault** [comment]
> Internal Proj Error: curl_easy_setopt at line 1605

If that refers to current PROJ master, that would be https://github.com/OSGeo/PROJ/blob/312e511cded7e29d23c5ff5ebf5f1be0bcdc44bb/src/networkfilemanager.cpp#L1605 that sets CURLOPT_SUPPRESS_CONNECT_HEADERS
Looking at curl sources https://github.com/curl/curl/blob/46d4373ea7a0c2306daacdfb5825862cd94ff764/lib/setopt.c#L2895 , setting this can't fail.
So no idea why you get this error

**Comment by snowman2** [comment]
Thanks for looking into it @rouault 👍

**Pull request merged**
