### PR TITLE
initial wheel build process

### PR DESCRIPTION
**Pull request by snowman2**

### CODE REVIEW

**Comment by snowman2** [comment]
OSX wheels built successfully & fail tests:
https://travis-ci.com/pyproj4/pyproj-wheels/jobs/183600898#L2326
```
File "/Users/travis/build/pyproj4/pyproj-wheels/venv/lib/python3.6/site-packages/pyproj/__init__.py", line 456, in pyproj.transform
Failed example:
    '%9.3f %11.3f' % (x2,y2)
Expected:
    '569722.342 4268814.028'
Got:
    '      inf         inf'
```

**Comment by snowman2** [comment]
Linux wheels build but tests fail as well:
https://travis-ci.com/pyproj4/pyproj-wheels/jobs/183601901

**Comment by snowman2** [comment]
@jswhit the wheels are successfully building now. However, some of the tests are failing. Thoughts?

**Comment by snowman2** [comment]
@jswhit, I think the wheel issues here are related to the issues in the pyproj repo about not being able to find proj.db. I will need to debug this sometime.

**Comment by jswhit** [comment]
Would you like me to create a 2.0.1 release tag?

**Comment by snowman2** [comment]
Sure, a tag would be helpful. I am testing from the latest commit.. I will update it once you have the tag ready.

**Comment by snowman2** [comment]
@jswhit all wheels we care about are built and uploaded. This is includes osx 🎉

**Comment by jswhit** [comment]
v2.0.1rel tag created

**Comment by jswhit** [comment]
Great - looks like just windows wheels are missing.

**Comment by snowman2** [comment]
Yeah, multibuild does not do windows wheels. Those are a different beast. It will require more research for windows wheels.

**Comment by snowman2** [comment]
I updated to the tag v2.0.1rel in the current build. The previous wheels should be fine to use as well.

**Pull request merged**
